---
- name: Create postgres group
  group: name=postgres gid=514

- name: Create postgres user
  user: name=postgres uid=514 group=postgres

- name: Ensure apt repos are up to date
  apt: update_cache=yes

- name: Install postgres
  apt: name={{ item }}
  with_items:
  - postgresql
  - postgresql-client
  - libpq-dev
  - python-psycopg2

- name: Copy config file
  template: src=postgresql.conf.j2 dest=/etc/postgresql/9.4/main/postgresql.conf
  notify: Restart postgres

- name: Copy config file
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  notify: Restart postgres