#!/bin/bash
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Should-Start:      network-manager
# Should-Stop:       network-manager
# X-Start-Before:    $x-display-manager gdm kdm xdm wdm ldm sdm nodm
# X-Interactive:     true
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat
# Description: Tomcat
### END INIT INFO
#
# tomcat
#
# chkconfig: 234 20 80
# description:  Start up the Tomcat servlet engine.

# Source function library.
. /etc/init.d/functions


CATALINA_HOME="/var/tomcat"

/bin/su tomcat $CATALINA_HOME/bin/catalina.sh $1

RETVAL=$?
exit $RETVAL
